// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testr-server/src/main/protobuf/auth.proto

package io.kope.testr.protobuf.auth;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code server.AuthPermission}
   */
  public enum AuthPermission
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>READ = 0;</code>
     */
    READ(0, 0),
    /**
     * <code>CREATE = 1;</code>
     */
    CREATE(1, 1),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>READ = 0;</code>
     */
    public static final int READ_VALUE = 0;
    /**
     * <code>CREATE = 1;</code>
     */
    public static final int CREATE_VALUE = 1;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static AuthPermission valueOf(int value) {
      switch (value) {
        case 0: return READ;
        case 1: return CREATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AuthPermission>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AuthPermission> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AuthPermission>() {
            public AuthPermission findValueByNumber(int number) {
              return AuthPermission.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.kope.testr.protobuf.auth.Auth.getDescriptor().getEnumTypes().get(0);
    }

    private static final AuthPermission[] VALUES = values();

    public static AuthPermission valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private AuthPermission(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:server.AuthPermission)
  }

  /**
   * Protobuf enum {@code server.TokenType}
   */
  public enum TokenType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>USER = 0;</code>
     */
    USER(0, 0),
    /**
     * <code>EXECUTOR = 1;</code>
     */
    EXECUTOR(1, 1),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>USER = 0;</code>
     */
    public static final int USER_VALUE = 0;
    /**
     * <code>EXECUTOR = 1;</code>
     */
    public static final int EXECUTOR_VALUE = 1;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static TokenType valueOf(int value) {
      switch (value) {
        case 0: return USER;
        case 1: return EXECUTOR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TokenType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TokenType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TokenType>() {
            public TokenType findValueByNumber(int number) {
              return TokenType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.kope.testr.protobuf.auth.Auth.getDescriptor().getEnumTypes().get(1);
    }

    private static final TokenType[] VALUES = values();

    public static TokenType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TokenType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:server.TokenType)
  }

  public interface AuthenticationTokenDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.AuthenticationTokenData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .server.TokenType token_type = 1;</code>
     */
    int getTokenTypeValue();
    /**
     * <code>optional .server.TokenType token_type = 1;</code>
     */
    io.kope.testr.protobuf.auth.Auth.TokenType getTokenType();

    /**
     * <code>optional string job = 2;</code>
     */
    java.lang.String getJob();
    /**
     * <code>optional string job = 2;</code>
     */
    com.google.protobuf.ByteString
        getJobBytes();

    /**
     * <code>optional string revision = 3;</code>
     */
    java.lang.String getRevision();
    /**
     * <code>optional string revision = 3;</code>
     */
    com.google.protobuf.ByteString
        getRevisionBytes();

    /**
     * <code>optional int64 timestamp = 4;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code server.AuthenticationTokenData}
   */
  public  static final class AuthenticationTokenData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:server.AuthenticationTokenData)
      AuthenticationTokenDataOrBuilder {
    // Use AuthenticationTokenData.newBuilder() to construct.
    private AuthenticationTokenData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AuthenticationTokenData() {
      tokenType_ = 0;
      job_ = "";
      revision_ = "";
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AuthenticationTokenData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              tokenType_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              job_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              revision_ = s;
              break;
            }
            case 32: {

              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.kope.testr.protobuf.auth.Auth.internal_static_server_AuthenticationTokenData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.kope.testr.protobuf.auth.Auth.internal_static_server_AuthenticationTokenData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData.class, io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData.Builder.class);
    }

    public static final int TOKEN_TYPE_FIELD_NUMBER = 1;
    private int tokenType_;
    /**
     * <code>optional .server.TokenType token_type = 1;</code>
     */
    public int getTokenTypeValue() {
      return tokenType_;
    }
    /**
     * <code>optional .server.TokenType token_type = 1;</code>
     */
    public io.kope.testr.protobuf.auth.Auth.TokenType getTokenType() {
      io.kope.testr.protobuf.auth.Auth.TokenType result = io.kope.testr.protobuf.auth.Auth.TokenType.valueOf(tokenType_);
      return result == null ? io.kope.testr.protobuf.auth.Auth.TokenType.UNRECOGNIZED : result;
    }

    public static final int JOB_FIELD_NUMBER = 2;
    private volatile java.lang.Object job_;
    /**
     * <code>optional string job = 2;</code>
     */
    public java.lang.String getJob() {
      java.lang.Object ref = job_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        job_ = s;
        return s;
      }
    }
    /**
     * <code>optional string job = 2;</code>
     */
    public com.google.protobuf.ByteString
        getJobBytes() {
      java.lang.Object ref = job_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        job_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REVISION_FIELD_NUMBER = 3;
    private volatile java.lang.Object revision_;
    /**
     * <code>optional string revision = 3;</code>
     */
    public java.lang.String getRevision() {
      java.lang.Object ref = revision_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        revision_ = s;
        return s;
      }
    }
    /**
     * <code>optional string revision = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRevisionBytes() {
      java.lang.Object ref = revision_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        revision_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tokenType_ != io.kope.testr.protobuf.auth.Auth.TokenType.USER.getNumber()) {
        output.writeEnum(1, tokenType_);
      }
      if (!getJobBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, job_);
      }
      if (!getRevisionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, revision_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tokenType_ != io.kope.testr.protobuf.auth.Auth.TokenType.USER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, tokenType_);
      }
      if (!getJobBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, job_);
      }
      if (!getRevisionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, revision_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.AuthenticationTokenData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.AuthenticationTokenData)
        io.kope.testr.protobuf.auth.Auth.AuthenticationTokenDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.kope.testr.protobuf.auth.Auth.internal_static_server_AuthenticationTokenData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.kope.testr.protobuf.auth.Auth.internal_static_server_AuthenticationTokenData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData.class, io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData.Builder.class);
      }

      // Construct using io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tokenType_ = 0;

        job_ = "";

        revision_ = "";

        timestamp_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.kope.testr.protobuf.auth.Auth.internal_static_server_AuthenticationTokenData_descriptor;
      }

      public io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData getDefaultInstanceForType() {
        return io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData.getDefaultInstance();
      }

      public io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData build() {
        io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData buildPartial() {
        io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData result = new io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData(this);
        result.tokenType_ = tokenType_;
        result.job_ = job_;
        result.revision_ = revision_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData) {
          return mergeFrom((io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData other) {
        if (other == io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData.getDefaultInstance()) return this;
        if (other.tokenType_ != 0) {
          setTokenTypeValue(other.getTokenTypeValue());
        }
        if (!other.getJob().isEmpty()) {
          job_ = other.job_;
          onChanged();
        }
        if (!other.getRevision().isEmpty()) {
          revision_ = other.revision_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int tokenType_ = 0;
      /**
       * <code>optional .server.TokenType token_type = 1;</code>
       */
      public int getTokenTypeValue() {
        return tokenType_;
      }
      /**
       * <code>optional .server.TokenType token_type = 1;</code>
       */
      public Builder setTokenTypeValue(int value) {
        tokenType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .server.TokenType token_type = 1;</code>
       */
      public io.kope.testr.protobuf.auth.Auth.TokenType getTokenType() {
        io.kope.testr.protobuf.auth.Auth.TokenType result = io.kope.testr.protobuf.auth.Auth.TokenType.valueOf(tokenType_);
        return result == null ? io.kope.testr.protobuf.auth.Auth.TokenType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .server.TokenType token_type = 1;</code>
       */
      public Builder setTokenType(io.kope.testr.protobuf.auth.Auth.TokenType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        tokenType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .server.TokenType token_type = 1;</code>
       */
      public Builder clearTokenType() {
        
        tokenType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object job_ = "";
      /**
       * <code>optional string job = 2;</code>
       */
      public java.lang.String getJob() {
        java.lang.Object ref = job_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          job_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string job = 2;</code>
       */
      public com.google.protobuf.ByteString
          getJobBytes() {
        java.lang.Object ref = job_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          job_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string job = 2;</code>
       */
      public Builder setJob(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        job_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string job = 2;</code>
       */
      public Builder clearJob() {
        
        job_ = getDefaultInstance().getJob();
        onChanged();
        return this;
      }
      /**
       * <code>optional string job = 2;</code>
       */
      public Builder setJobBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        job_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object revision_ = "";
      /**
       * <code>optional string revision = 3;</code>
       */
      public java.lang.String getRevision() {
        java.lang.Object ref = revision_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          revision_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string revision = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRevisionBytes() {
        java.lang.Object ref = revision_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          revision_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string revision = 3;</code>
       */
      public Builder setRevision(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        revision_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string revision = 3;</code>
       */
      public Builder clearRevision() {
        
        revision_ = getDefaultInstance().getRevision();
        onChanged();
        return this;
      }
      /**
       * <code>optional string revision = 3;</code>
       */
      public Builder setRevisionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        revision_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:server.AuthenticationTokenData)
    }

    // @@protoc_insertion_point(class_scope:server.AuthenticationTokenData)
    private static final io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData();
    }

    public static io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthenticationTokenData>
        PARSER = new com.google.protobuf.AbstractParser<AuthenticationTokenData>() {
      public AuthenticationTokenData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new AuthenticationTokenData(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<AuthenticationTokenData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthenticationTokenData> getParserForType() {
      return PARSER;
    }

    public io.kope.testr.protobuf.auth.Auth.AuthenticationTokenData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SignedTokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.SignedToken)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes data = 1;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>optional int32 key_id = 2;</code>
     */
    int getKeyId();

    /**
     * <code>optional bytes signature = 3;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code server.SignedToken}
   */
  public  static final class SignedToken extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:server.SignedToken)
      SignedTokenOrBuilder {
    // Use SignedToken.newBuilder() to construct.
    private SignedToken(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SignedToken() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      keyId_ = 0;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SignedToken(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              data_ = input.readBytes();
              break;
            }
            case 16: {

              keyId_ = input.readInt32();
              break;
            }
            case 26: {

              signature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.kope.testr.protobuf.auth.Auth.internal_static_server_SignedToken_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.kope.testr.protobuf.auth.Auth.internal_static_server_SignedToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.kope.testr.protobuf.auth.Auth.SignedToken.class, io.kope.testr.protobuf.auth.Auth.SignedToken.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 1;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int KEY_ID_FIELD_NUMBER = 2;
    private int keyId_;
    /**
     * <code>optional int32 key_id = 2;</code>
     */
    public int getKeyId() {
      return keyId_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>optional bytes signature = 3;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      if (keyId_ != 0) {
        output.writeInt32(2, keyId_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(3, signature_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (keyId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, keyId_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, signature_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static io.kope.testr.protobuf.auth.Auth.SignedToken parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.kope.testr.protobuf.auth.Auth.SignedToken parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.kope.testr.protobuf.auth.Auth.SignedToken parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.kope.testr.protobuf.auth.Auth.SignedToken parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.kope.testr.protobuf.auth.Auth.SignedToken parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.kope.testr.protobuf.auth.Auth.SignedToken parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.kope.testr.protobuf.auth.Auth.SignedToken parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.kope.testr.protobuf.auth.Auth.SignedToken parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.kope.testr.protobuf.auth.Auth.SignedToken parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.kope.testr.protobuf.auth.Auth.SignedToken parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.kope.testr.protobuf.auth.Auth.SignedToken prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.SignedToken}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.SignedToken)
        io.kope.testr.protobuf.auth.Auth.SignedTokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.kope.testr.protobuf.auth.Auth.internal_static_server_SignedToken_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.kope.testr.protobuf.auth.Auth.internal_static_server_SignedToken_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.kope.testr.protobuf.auth.Auth.SignedToken.class, io.kope.testr.protobuf.auth.Auth.SignedToken.Builder.class);
      }

      // Construct using io.kope.testr.protobuf.auth.Auth.SignedToken.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;

        keyId_ = 0;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.kope.testr.protobuf.auth.Auth.internal_static_server_SignedToken_descriptor;
      }

      public io.kope.testr.protobuf.auth.Auth.SignedToken getDefaultInstanceForType() {
        return io.kope.testr.protobuf.auth.Auth.SignedToken.getDefaultInstance();
      }

      public io.kope.testr.protobuf.auth.Auth.SignedToken build() {
        io.kope.testr.protobuf.auth.Auth.SignedToken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.kope.testr.protobuf.auth.Auth.SignedToken buildPartial() {
        io.kope.testr.protobuf.auth.Auth.SignedToken result = new io.kope.testr.protobuf.auth.Auth.SignedToken(this);
        result.data_ = data_;
        result.keyId_ = keyId_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.kope.testr.protobuf.auth.Auth.SignedToken) {
          return mergeFrom((io.kope.testr.protobuf.auth.Auth.SignedToken)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.kope.testr.protobuf.auth.Auth.SignedToken other) {
        if (other == io.kope.testr.protobuf.auth.Auth.SignedToken.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getKeyId() != 0) {
          setKeyId(other.getKeyId());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.kope.testr.protobuf.auth.Auth.SignedToken parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.kope.testr.protobuf.auth.Auth.SignedToken) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 1;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 1;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private int keyId_ ;
      /**
       * <code>optional int32 key_id = 2;</code>
       */
      public int getKeyId() {
        return keyId_;
      }
      /**
       * <code>optional int32 key_id = 2;</code>
       */
      public Builder setKeyId(int value) {
        
        keyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 key_id = 2;</code>
       */
      public Builder clearKeyId() {
        
        keyId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signature = 3;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>optional bytes signature = 3;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signature = 3;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:server.SignedToken)
    }

    // @@protoc_insertion_point(class_scope:server.SignedToken)
    private static final io.kope.testr.protobuf.auth.Auth.SignedToken DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.kope.testr.protobuf.auth.Auth.SignedToken();
    }

    public static io.kope.testr.protobuf.auth.Auth.SignedToken getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignedToken>
        PARSER = new com.google.protobuf.AbstractParser<SignedToken>() {
      public SignedToken parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new SignedToken(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<SignedToken> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignedToken> getParserForType() {
      return PARSER;
    }

    public io.kope.testr.protobuf.auth.Auth.SignedToken getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_server_AuthenticationTokenData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_server_AuthenticationTokenData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_server_SignedToken_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_server_SignedToken_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)testr-server/src/main/protobuf/auth.pr" +
      "oto\022\006server\"r\n\027AuthenticationTokenData\022%" +
      "\n\ntoken_type\030\001 \001(\0162\021.server.TokenType\022\013\n" +
      "\003job\030\002 \001(\t\022\020\n\010revision\030\003 \001(\t\022\021\n\ttimestam" +
      "p\030\004 \001(\003\">\n\013SignedToken\022\014\n\004data\030\001 \001(\014\022\016\n\006" +
      "key_id\030\002 \001(\005\022\021\n\tsignature\030\003 \001(\014*&\n\016AuthP" +
      "ermission\022\010\n\004READ\020\000\022\n\n\006CREATE\020\001*#\n\tToken" +
      "Type\022\010\n\004USER\020\000\022\014\n\010EXECUTOR\020\001B\035\n\033io.kope." +
      "testr.protobuf.authb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_server_AuthenticationTokenData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_AuthenticationTokenData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_server_AuthenticationTokenData_descriptor,
        new java.lang.String[] { "TokenType", "Job", "Revision", "Timestamp", });
    internal_static_server_SignedToken_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_SignedToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_server_SignedToken_descriptor,
        new java.lang.String[] { "Data", "KeyId", "Signature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
